"use client";
import { useState } from "react";

type Candidate = { citation_ref: string; domain: string; age_status: string; action: string; observation: string; follow_up_en: string; follow_up_ur_latn: string; sources: { source_id: string }[]; match_tokens: number };
type PreviewResult = { candidates: Candidate[] };

export default function KnowledgePreviewPage() {
  const [form, setForm] = useState({ observation: "", age_lower_months: 24, age_upper_months: 36, domain: "" });
  const [result, setResult] = useState<PreviewResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function run(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError("");
    try { const r = await fetch("/api/admin/knowledge/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, age_lower_months: Number(form.age_lower_months), age_upper_months: Number(form.age_upper_months), domain: form.domain || null }) }); const j = await r.json(); if (!r.ok) throw new Error(j.detail || "Preview failed"); setResult(j.data); } catch (e) { setError(e instanceof Error ? e.message : "Preview failed"); } finally { setBusy(false); }
  }
  return <main className="mx-auto w-full max-w-5xl space-y-6 p-5 sm:p-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-ink-muted">Research sandbox</p><h1 className="mt-2 font-display text-3xl font-bold text-ink">V3 knowledge preview</h1><p className="mt-2 max-w-2xl text-sm text-ink-soft">Inspect age/domain retrieval and follow-up wording against the draft KB. This never grades, diagnoses, or writes a session.</p></div>
    <form onSubmit={run} className="rounded-xl border border-line bg-surface p-5 space-y-4"><textarea required value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})} placeholder="Synthetic observation…" className="min-h-28 w-full rounded-lg border border-line bg-canvas p-3 text-sm" /><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-ink-soft">Age from (months)<input type="number" min="0" max="216" value={form.age_lower_months} onChange={e=>setForm({...form,age_lower_months:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2 text-sm" /></label><label className="text-xs text-ink-soft">Age to (months)<input type="number" min="0" max="216" value={form.age_upper_months} onChange={e=>setForm({...form,age_upper_months:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2 text-sm" /></label><label className="text-xs text-ink-soft">Domain<select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})} className="mt-1 w-full rounded-lg border border-line bg-canvas p-2 text-sm"><option value="">All domains</option>{["Speech_Language","Hearing","Vision","Motor","Social_Communication","Attention","Attachment","Safety","Safeguarding"].map(x=><option key={x}>{x}</option>)}</select></label></div><button disabled={busy} className="rounded-lg bg-ink px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Inspecting…" : "Run preview"}</button>{error&&<p className="text-sm text-red-700">{error}</p>}</form>
    {result && <section className="space-y-3"><div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Preview only · runtime disabled · clinical grade: none</div>{result.candidates.map((c)=><article key={c.citation_ref} className="rounded-xl border border-line bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-ink">{c.citation_ref} · {c.domain}</h2><span className="text-xs text-ink-muted">{c.age_status} · {c.action}</span></div><p className="mt-2 text-sm text-ink">{c.observation}</p><p className="mt-2 text-sm text-ink-soft"><b>Follow-up:</b> {c.follow_up_en}</p><p className="mt-1 text-sm text-ink-soft">{c.follow_up_ur_latn}</p><p className="mt-2 text-xs text-ink-muted">Evidence: {c.sources.map((s)=>s.source_id).join(", ")} · match tokens {c.match_tokens}</p></article>)}</section>}</main>;
}
